plugins:
   - jekyll-avatar
   - jekyll-mentions
   - jekyll-sitemap
   - jekyll-feed
   - jemoji
permalink: /blog/:categories/:title/
kramdown:
  auto_ids: false
title: Bob Pony Blog
description: The source of the how-tos and updates!
